name: publish
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  publish-jars:
    runs-on: self-hosted
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.9_2.12.19
      options: --user 1001:1001
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: sbt publish
      run: sbt clean publish
  publish-docker-image:
    runs-on: self-hosted
    outputs:
      should_trigger_deploy: ${{ steps.publish-docker-image.outputs.should_trigger_deploy }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.WRITE_PACKAGES }}
        logout: false
    - name: publish docker images
      run: .github/scripts/dnd-sbt docker/Docker/publish
    - name: set should_trigger_deploy
      id: should_trigger_deploy
      shell: bash
      run: |
        pattern='^refs/tags/v[0-9]+\.[0-9]+\.(?:[1-9][0-9]*|[0-9]+-.*)$'
        echo "should_trigger_deploy=$([[ "$GITHUB_REF" =~ $pattern ]] && echo true || echo false)" >> $GITHUB_OUTPUT
  trigger-deploy:
      needs: publish-docker-image
      if: needs.publish-docker-image.outputs.should_trigger_deploy == 'true'
      runs-on: ubuntu-latest
      steps:
        - name: tag without 'v' prefix
          id: extract_tag
          run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        - name: trigger mvp-deployer workflow
          uses: peter-evans/repository-dispatch@v2
          with:
            token: ${{ secrets.RAW_CI_PAT }}
            repository: raw-labs/mvp-deployer
            event-type: deploy-patch
            client-payload: |
              {
                "raw_version": "${{ steps.extract_tag.outputs.raw_version }}",
                "target_env": "integration",
                "loaded_vars": "integration"
              }
